#!/bin/bash

function print_usage() {
  printf "Syntax: $0 <iv-hex> <password-plain> <ciphertext-b64>\n";
}
# --------------------------------------------------------------------

function decrypt() {
  IV="$1"
  KEY="$(printf "$2" | sha256sum | cut -d '-' -f 1 | awk '{print $1}')"
  CIPHERTEXT="$3"
  
  DEC=$(echo "$CIPHERTEXT" | openssl aes-256-cbc -d -a -K "$KEY" -iv "$IV" -nopad) # 2> /dev/null)
  if [ $? -eq 0 ]; then
    printf "$DEC\n"
  else
    printf "Decryption failed\n"
  fi

}
# --------------------------------------------------------------------

if [ ! -n "$1" -o ! -n "$2" -o ! -n "$3" ]; then
  print_usage
  exit 1
fi

decrypt "$1" "$2" "${3//%2b/+}"

exit 0
